require("mappings.general")
require("mappings.ui")
require("mappings.buffers")
require("mappings.snacks")
require("mappings.find")
require("mappings.git")
require("mappings.lsp")
require("mappings.tabs")
