theme = "light:GitLab Light, dark:GitLab Dark"
title = "ghostty"

font-size = 17
font-thicken = true
font-thicken-strength = 0
font-family = "psudoFont Liga Mono"

macos-icon = "blueprint"
macos-window-buttons = "hidden"
macos-titlebar-proxy-icon = "hidden"
macos-titlebar-style = "hidden"

cursor-opacity = "0.8"
cursor-color = "cell-foreground"
cursor-invert-fg-bg = true
mouse-hide-while-typing = "true"
adjust-cell-height = 11
minimum-contrast = 1.5

window-colorspace = "display-p3"
window-padding-balance = true
window-decoration = "none"

keybind = ctrl+comma=text:\x15
