let mapleader = " "

let s:config_dir = fnamemodify(resolve(expand('<sfile>:p')), ':h')
execute 'source ' . s:config_dir . '/options.vim'
execute 'source ' . s:config_dir . '/plugins.vim'
execute 'source ' . s:config_dir . '/mappings.vim'

let s:local_config = s:config_dir . '/configs/options.local.vim'
if filereadable(s:local_config)
  execute 'source ' . s:local_config
endif
unlet s:config_dir s:local_config
