set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @tmux-dotbar-right true
set -g @tmux-dotbar-status-right-text "%I:%M %p 󰥔 "
set -g @tmux-dotbar-bold-current-window true

# Match tmux-dotbar to GitLab Light palette
set -g @tmux-dotbar-bg "#fafaff"           # Crisp white background (or "default" for transparent)
set -g @tmux-dotbar-fg "#8c8d99"           # Soft gray for inactive windows
set -g @tmux-dotbar-fg-current "#2e2e38"   # Dark slate for active window text
set -g @tmux-dotbar-fg-session "#2e2e38"   # Subtle GitLab soft blue for session name
set -g @tmux-dotbar-fg-prefix "#6b4fbb"    # Deep muted purple accent when prefix key is pressed
set -g @tmux-dotbar-session-text "  #S "        # Icon + Session name (requires Nerd Fonts)

